"""empty message

Revision ID: 24b8a00223d3
Revises: 
Create Date: 2017-11-11 18:33:09.857104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b8a00223d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mentors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mentees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentees_email'), 'mentees', ['email'], unique=True)
    op.create_index(op.f('ix_mentees_first_name'), 'mentees', ['first_name'], unique=False)
    op.create_index(op.f('ix_mentees_last_name'), 'mentees', ['last_name'], unique=False)
    op.create_index(op.f('ix_mentees_username'), 'mentees', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentees_username'), table_name='mentees')
    op.drop_index(op.f('ix_mentees_last_name'), table_name='mentees')
    op.drop_index(op.f('ix_mentees_first_name'), table_name='mentees')
    op.drop_index(op.f('ix_mentees_email'), table_name='mentees')
    op.drop_table('mentees')
    op.drop_table('mentors')
    op.drop_table('departments')
    # ### end Alembic commands ###
